### ISSUE TITLE
bug: regenerated runtime prelude emits conflicting duplicate declares (sfn_print/sfn_array_concat) — breaks `sfn test`/`make check`

### ISSUE THREAD

**Issue by mcereal** [SailfinIO/sailfin#1736]
## Goal

Fix the duplicate **conflicting-signature** runtime-helper `declare`s emitted into the regenerated runtime prelude module, so `sfn test` / `sfn build` / `sfn run` and `make check`'s test phase link again.

## Symptom

Any `sfn test` / `make test-unit` / `make check` test run fails at link:

```
build/sailfin/sfn__runtime-native__prelude.sfn-O0.ll:206:13: error: invalid redefinition of function 'sfn_array_concat'
  206 | declare i8* @sfn_array_concat(i8*, i8*)
sfn build: failed to compile runtime sfn-source object .../sfn__runtime-native__prelude.sfn-O0.o
link failed (clang exit=1)
```

The regenerated prelude `.ll` declares `sfn_print` and `sfn_array_concat` **twice with different signatures**:

```
declare void @sfn_print({i8*, i64})        # descriptor-typed (length-aware string ABI)
declare void @sfn_print(i8*, i64)          # erased import-closure
declare { i8**, i64, i64 }* @sfn_array_concat({ i8**, i64, i64 }*, { i8**, i64, i64 }*)
declare i8* @sfn_array_concat(i8*, i8*)
```

clang's per-module verifier rejects the conflicting pair.

## Pre-existing & environment scope

This is **not** introduced by the #1627 effect-hardening branch — the pristine pinned **seed** (`build/seed/bin/sailfin`, 0.7.0-alpha.49) reproduces it identically on a clean cache. Likely introduced by `ed94c39 feat(runtime): length-aware ({i8*, i64}) ABI for query-side string helpers (#1719)` on `main`. `make compile`'s *build* phase avoids it because it compiles the compiler capsule's internal `prelude_scan`/`prelude_globals` sub-modules (`build/native/raw/*.ll`), which run only the typed descriptor declare pass — never the transitive imported-function declare pass that produces the erased duplicate.

## Root cause

When `sfn build`/`run`/`test` compile the runtime prelude as a runtime sfn-source, two independent declare-emission passes both emit a `declare` for the cross-module helpers `sfn_print` / `sfn_array_concat`:

- `render_runtime_helper_declarations` (`compiler/src/llvm/rendering.sfn`) emits the **descriptor-typed** shape from the runtime-helper registry (`runtime_helpers.sfn:156` `print` → `{i8*,i64}`; `:1439` `concat` → `{i8**,i64,i64}*`).
- `render_imported_function_declarations` (`rendering.sfn:383`) independently emits the **source-level erased** shape from the prelude's transitive import closure, matching the true definitions in `runtime/sfn/io.sfn:287` (`sfn_print(* u8, i64)`) and `runtime/sfn/array.sfn:418` (`sfn_array_concat(* u8, * u8) -> * u8`).

The two passes do not share a `declared_symbols` set. The registry pass *has* an import-shadow skip (`rendering.sfn:316-325`) but it is gated on `descriptor.target == descriptor.symbol`; for `print` (`target="print"`, `symbol="sfn_print"`) and `concat` (`target="concat"`, `symbol="sfn_array_concat"`) the target differs from the symbol, so the skip is bypassed and both declares survive.

Both passes are invoked into the same module at `compiler/src/llvm/lowering/lowering_phase_render.sfn:146` and `:156`.

## Proposed fix (to validate)

In `compiler/src/llvm/rendering.sfn`, dedupe by **symbol** across the two passes: either extend the import-shadow skip to fire on `descriptor.symbol` collisions regardless of `target == symbol`, or share one `declared_symbols` set between the typed-descriptor and imported-function passes. NOTE: the prelude's own call sites use the **typed descriptor** signature (e.g. `call {i8**,i64,i64}* @sfn_array_concat(...)`), so the surviving declare must be the **typed** one (the typed declare must win, not the erased import declare) — verify the chosen dedup keeps the declare consistent with the emitted calls.

## Acceptance Criteria

- [ ] A regenerated `build/sailfin/sfn__runtime-native__prelude.sfn-O0.ll` declares each runtime helper exactly once with a signature consistent with its call sites.
- [ ] `sfn test` / `make test-unit` link and run (a trivial `test "t" [pure] { assert true; }` passes).
- [ ] `make compile` still self-hosts; `make check` green.

## Relationships

- Surfaced while validating #1627 (effect-system hardening, epic #1180) — this blocker prevents running that work's regression suite in a fresh environment.
- Likely introduced by #1719 (`ed94c39`).

## Files Affected

`compiler/src/llvm/rendering.sfn` (declare emitters), `compiler/src/llvm/lowering/lowering_phase_render.sfn`, `compiler/src/llvm/runtime_helpers.sfn` (descriptor rows), references `runtime/sfn/io.sfn`, `runtime/sfn/array.sfn`.

## Size

S

## Type

Bug
