### PR TITLE
docs(typecheck): document E0420 undefined-function policy + regression corpus

### LINKED ISSUE #813: docs(typecheck): document undefined-function policy + allowlist envelope
Sub-issue of #616.

## Goal
Lock the E0420 undefined-function policy in docs and add a regression corpus so the auto-injection envelope can't silently drift.

## Scope
**In:**
- Add the E0420 policy + the full builtin/keyword envelope to `docs/status.md` (typecheck feature row).
- Document undefined-function rejection + the allowlist in the relevant spec chapter under `site/src/content/docs/docs/reference/spec/` (name-resolution / statements §).
- Add a one-line note to `examples/README.md` that undefined function calls are now a compile error.
- Update `llms.txt` with E0420.
- Add an integration test that runs `sfn check` over a fixture asserting exit code + message text.

**Out:**
- New language behavior.
- Member-resolution docs.

## Acceptance Criteria
- [ ] `docs/status.md` lists E0420 and the envelope set.
- [ ] Spec chapter documents undefined-function rejection and the allowlist.
- [ ] `examples/README.md` mentions the policy.
- [ ] `llms.txt` updated with E0420.
- [ ] Integration test `undefined_function_check_test.sfn` asserts `sfn check` exit code + `E0420` string on a fixture.
- [ ] make compile passes
- [ ] make test passes
- [ ] `sfn fmt --check` clean on every touched `.sfn` file

## Files Affected
- `docs/status.md`
- `site/src/content/docs/docs/reference/spec/<chapter>.md`
- `examples/README.md`
- `llms.txt`
- `compiler/tests/integration/undefined_function_check_test.sfn` — new

## Verification
```bash
ulimit -v 8388608 && make test-integration
```

## Size
XS

## Type
Docs

## Blocked by
#812

## Required in pinned seed
None — docs + test only.

## Context
- Closes the documentation half of #616's acceptance criteria ("a passing test asserts the auto-injection envelope and examples/README.md mentions the policy").
- Envelope members defined in #810 (`is_builtin_call_name`).
- Fifth of 5 sub-issues decomposing #616.

### PR DESCRIPTION
**Pull request by mcereal**
## Summary
- Locks the **E0420** undefined-function policy in docs (status, spec, examples, `llms.txt`) so the resolution order and builtin/runtime envelope are written down.
- Adds an integration regression test driving the shipped `sfn check` binary over a fixture, so the auto-injection envelope can't silently drift without a red CI run.

Closes #813 (documentation/test half of #616; enforcement flip shipped in #812).

## Acceptance Criteria
- [x] `docs/status.md` lists E0420 and the envelope set (narrative bullet under *Compiler Pipeline* + a Feature Matrix row).
- [x] Spec chapter documents undefined-function rejection and the allowlist (§5 Expressions — *Function calls and name resolution*).
- [x] `examples/README.md` mentions the policy.
- [x] `llms.txt` updated with E0420.
- [x] Integration test `undefined_function_check_test.sfn` asserts `sfn check` exit code + `E0420` string on a fixture (plus a defined-callee negative case).
- [x] `make compile` passes (no `compiler/src/` changes; compiler self-hosted at exit 0).
- [x] `make test` passes (integration suite 29/29).
- [x] `sfn fmt --check` clean on the touched `.sfn` file.

## Documented resolution order
A bare-`Identifier` callee must resolve to one of, else E0420:
1. **In-scope bindings** — params, locals, top-level `fn`/`extern fn`, import-specifier names.
2. **Builtin envelope** (`is_builtin_call_name`) — `print`, `console`, `assert`, `spawn`, `sleep`, `serve`, `channel`, `send`, `receive`, `await`, and the six `atomic_*` intrinsics.
3. **Implicit prelude / `runtime/sfn/**` globals** — scanned via `prelude_globals.sfn`, callable without an `import`.
4. **Localized import table** (`lookup_imported_function`).

Out of scope (matches #812): member/method callees (`obj.method()`), undefined *variable* refs, and argument *type* checks.

## Verification
```bash
ulimit -v 8388608 && make test-integration
# ═══ integration: 29/29 passed, 0 failed ═══
#   undefined_function_check_test.sfn → PASS (all 2 tests passed)

ulimit -v 8388608 && build/native/sailfin fmt --check \
  compiler/tests/integration/undefined_function_check_test.sfn   # clean
```
Live fixture behavior confirmed: undefined callee → `error[E0420]: undefined function ...`, exit 1; defined callee → `checked 1 files: ok`, exit 0.

## Files Changed
- `docs/status.md`
- `site/src/content/docs/docs/reference/spec/05-expressions.md`
- `examples/README.md`
- `llms.txt`
- `compiler/tests/integration/undefined_function_check_test.sfn` (new)

## Note
One flaky `closure_lifting_test.sfn` SIGSEGV (Error 139) appeared on the first full-suite run — a known order/memory-pressure flake under the 8GB cap. It passes in isolation (rc=0) and the suite re-ran clean at 29/29. Unrelated to this docs/test change.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

---
_Generated by [Claude Code](https://claude.ai/code/session_01Ekrv91vxQsXunXRQa7uFd5)_

### CODE REVIEW

**Comment by mcereal** [comment]
Thanks for the review. Addressed in `cc9cc9e`:

**Temp-fixture paths (lines 63, 74) — fixed.** Fixtures now come from a kernel-unique `fs.mkdtemp("sfn-e0420-")` scratch dir instead of fixed `/tmp/<name>.sfn`, so concurrent `sfn test` runs can't collide, and the fixture file is deleted afterward. (The `fs` surface has no `rmdir` primitive, so only the empty unique dir is left behind — strictly less residue than the previous fixed path.)

**Empty `env_flat` / PATH (lines 41, 50) — keeping empty, intentionally.** The empty environment is deliberate here, and I've added a comment saying so:
- The binary is launched by an explicit slashed path (`build/native/sailfin`), so `posix_spawnp` never consults `PATH` for the spawn.
- `sfn check`'s runtime-root resolution is exe-relative (`exe_path()` → `resolve_runtime_root`), not environment-driven, so the implicit prelude/`runtime/sfn/**` envelope still resolves under an empty env (the negative case proves it).
- `sfn check`'s only env knobs are `SAILFIN_EFFECT_ENFORCE` and `SAILFIN_USE_ARENA`; they *must* stay unset so the test exercises the shipped defaults deterministically. Threading the ambient env through `env.get` would make the test pick up a developer's shell setting and become *less* hermetic — the opposite of what we want for a regression pin.

---
_Generated by [Claude Code](https://claude.ai/code)_
